# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'Finances' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Charts'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'SkeletonView'
  pod 'SwiftLint'

  # Pods for Finances

  target 'FinancesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinancesUITests' do
    # Pods for testing
  end

end
